<?php

namespace AppBundle\Repository;

/**
 * RegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllPlaticas() {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM AppBundle:Registro r WHERE r.titulo IS NOT NULL ORDER BY r.nombre ASC'
            )
            ->getResult();
    }

}
